## Numpy 배열 인덱싱 & 슬라이싱

In [6]:
import numpy as np
narray = np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
# 두번째 요소 출력
print(narray[1])
# 마지막 요소
print(narray[-1])
# 1~4까지 출력
print(narray[1:])
# 전부
print(narray[:])
# 2,3만
print(narray[2:4])

1
4
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [ ]:
'''
2차원 배열에서의 인덱싱, 슬라이싱
인덱스 : [행idx,열idx] == [행][열]
[:] 모든 행과 모든 열 포함
'''

In [23]:
# 매트릭스에서 인덱싱, 슬라이싱 사용
np.random.seed(100)
narray1 = np.random.randint(0,20,16).reshape(4,4)
narray1

array([[ 8,  3,  7, 15],
       [16, 10,  2,  2],
       [ 2, 14,  2, 17],
       [16, 15,  4, 11]])

In [50]:
### 문제1
#### narray1 객체에서 첫 행의 7 가져오기
narray1[0,2]
narray1[0][2]

# 문제2 : 2행 [16~2,2] 가져오기
print(narray1[1,0:4])
print(narray1[1,0:])
print(narray1[1,:])
print(narray1[1:2,:]) # 2차원 출력
print(narray1[1])

print('*'*30)
# 문제 3 : 전체행에 대해서 4번째 열만 다 가져오려면
print(np.shape(narray1))
print(narray1[:,3:]) # 2차원
print(narray1[:,3])

# 4. 전체 행에 대해서 1,2번째 열만 가져오기
print(narray1[:,:2])

[16 10  2  2]
[16 10  2  2]
[16 10  2  2]
[[16 10  2  2]]
[16 10  2  2]
******************************
(4, 4)
[[15]
 [ 2]
 [17]
 [11]]
[15  2 17 11]
[[ 8  3]
 [16 10]
 [ 2 14]
 [16 15]]


## 인덱싱과 조건 슬라이싱 (중요)

In [79]:
np.random.seed(0)
arr3 = np.random.randn(4,4)

In [62]:
# 1. 논리연산자 사용
print(np.size(arr3[arr3>0]))
print(arr3[arr3>0])

# 2. 0보다 작은 값들을 0으로 치환
arr3[arr3<0]=0 # 원본도 바뀌니까 가능
arr3

13
[1.76405235 0.40015721 0.97873798 2.2408932  1.86755799 0.95008842
 0.4105985  0.14404357 1.45427351 0.76103773 0.12167502 0.44386323
 0.33367433]


array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [65]:
#3. where 함수
'''
arr3>0 크면 arr3 그대로 리턴
arr3<0 작으면 -1 리턴
'''
arr3_1=np.where(arr3!=0,arr3,-1) # 사망연산자 생각 (조건, 트루면 , 폴스면 )
arr3_1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -1.        ,  0.95008842, -1.        ],
       [-1.        ,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [70]:
# 매커니즘 : 하나하나 돌면서 boolean 연산을 함
a=np.array([[1,2],[3,4],[5,6]])
bool_a = (a>2)
bool_a

# a의 요소로 넣으면 추린 것만 리턴됨
print(a[a>2])

[3 4 5 6]


## Numpy 통계함수

In [80]:
arr4 = np.random.randint(0,20,16).reshape(4,4)
arr4

array([[18,  3, 17, 19],
       [19, 19, 14,  7],
       [ 0,  1,  9,  0],
       [10,  3, 11, 18]])

In [90]:
'''
Numpy 계열 통계함수
sum(), mean(), min(), max(), argmin(), argmax(), cumsum() : 누적합
'''
# 1. sum()
print(np.sum(arr4))
# np.sum?
# axis 속성 : None = 전부다, 0 = 모든행/세로, 1 = 모든열/가로

print(np.sum(arr4,axis=0))
'''
axis = 0
모든 행 다 검색
그 중에서 가장 큰 값의 인덱스 검색
'''
print(np.argmax(arr4,axis=0))

168
[47 26 51 44]
[1 1 0 0]
