### Pytorch에서의 Gradient Descent

In [2]:
'''
우리는 ML 과정에서 선형회귀(Linear Regression)에 대해 간단히 살펴봄
이번에는 파이토치를 이용해서 선형회귀를 위한 연산 그래프를 만들고
경사하강법을 이해하는 코드를 다시 작성해 봅니다.

파이토치에서는 데이터의 기본단위로 Tensor를 사용합니다
Tensor란? Numpy에서 np.array([1,2,3]) 와 동일
이러한 텐서를 연산의 기본단위로 사용한다.

텐서를 생성하는 방법으로는
1) torch.tensor()
2) addtensor ()
등등이 있다
'''

'\n우리는 ML 과정에서 선형회귀(Linear Regression)에 대해 간단히 살펴봄\n이번에는 파이토치를 이용해서 선형회귀를 위한 연산 그래프를 만들고\n경사하강법을 이해하는 코드를 다시 작성해 봅니다.\n\n파이토치에서는 데이터의 기본단위로 Tensor를 사용합니다\nTensor란? Numpy에서 np.array([1,2,3]) 와 동일\n이러한 텐서를 연산의 기본단위로 사용한다.\n\n텐서를 생성하는 방법으로는\n1) torch.tensor()\n'

In [28]:
# pytorch Framework 불러오기
import torch
# pytorchvision 은 Image Processing에 특화된 라이브러리
import torchvision
# nn subset : Neural Net에 관한 특화된 라이브러리
import torch.nn as nn
# Image Augmentation 관련 라이브러리
import torchvision.transforms as transforms
import numpy as np

In [14]:
# 2행 3열의 행렬을 0에 가까운 값으로 자동으로 초기화된 채로 나옴
X = torch.Tensor(2,3)
X
X.shape
X.size()

# 직접 값 넣기
X = torch.Tensor([[1,2,3,],[4,5,6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
'''
tensor() 사용하기
::
함수의 인자값으로 data.dtype, device, requires_grad 등이 있다
dtype : 데이터 타입 지정
device : 텐서를 어느 기기에 올릴 것인가를 지정... CPU or GPU
- 연산이 커지면 (DNN, CNN을 가면) GPU를 사용해야 한다
requires_grad : 텐서의 기울기를 지정할지의 여부... 기본값(False)
- 미분사용 여부
- Backpropagation 여부
- False : Test Model... 이미 학습한 걸... 자원을 덜 쓰겠다
- True : Training Model
'''
x = torch.tensor(data=[2.0,3], requires_grad = True)
# x = torch.tensor(data=[2.0,3])
x
y = x**2
y
# 1. 예측
pred = 2*y+3
pred

target = torch.tensor([3.0,4])
# 2. Loss 구하기
loss = torch.sum(torch.abs(pred-target)) # (11-3)+(21-4) = 25
print('loss = {}' .format(loss))

# 3. 가장 가파른 기울기로 하강하는 Weight를 찾기
# 가장 낮은 loss값을 결정하는 Weight를 찾기... 편미분...backpropagation
# requires_grad = False면 안 돌아감
loss.backward()

'''
x.grad ----> dy/dw = x ()
w.grad ----> dy/dx = w ()
'''
print(x.grad, pred.grad)

loss = 25.0
tensor([ 8., 12.]) None


### Tensor Type - tensor(), as_tensor()
####    numpy 배열을 Tensor type으로 바꾸기

In [90]:
'''
pytorch의 tensor 는 np의 array이와 같다
'''
#1.변환
li = np.array([[1,2,],[3,4]])
print(li)
print(li.dtype)
print(type(li))
print('*'*30)
li = torch.tensor(li)
print(li.dtype)
print(type(li))

#2.
li_as_torch = torch.as_tensor(li)
print('*'*30)
li = torch.tensor(li_as_torch)
print(li_as_torch.dtype)
print(type(li_as_torch))
print('*'*30)
# 반대로 tensor --> np.array로 변형
# torch.numpy() 사용
li=li.numpy()
print(li.dtype)
print(type(li))

[[1 2]
 [3 4]]
int32
<class 'numpy.ndarray'>
******************************
torch.int32
<class 'torch.Tensor'>
******************************
torch.int32
<class 'torch.Tensor'>
******************************
int32
<class 'numpy.ndarray'>


C:\kjy\anaconda3\lib\site-packages\ipykernel_launcher.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
