In [1]:
# pytorch Framework 불러오기
import torch
# pytorchvision 은 Image Processing에 특화된 라이브러리
import torchvision
# nn subset : Neural Net에 관한 특화된 라이브러리
import torch.nn as nn
# Image Augmentation 관련 라이브러리
import torchvision.transforms as transforms
import numpy as np

### Create Tensor ... Generating NN

In [33]:
x = torch.tensor(1.,requires_grad=True)
w = torch.tensor(2.,requires_grad=True)
b = torch.tensor(3.,requires_grad=True)

print('x,y,b = {},{},{}'.format(x,w,b))

x,y,b = 1.0,2.0,3.0


In [34]:
y = w*x + b # 1차원... y=2x+3

y.backward() # 미분됨

print(x.grad, w.grad, b.grad)

tensor(2.) tensor(1.) tensor(1.)


### Create Tensor... 2차원

In [216]:
x = torch.randn(10,3)
y = torch.randn(10,2)

# 1. NN 구성
# x*w+b=y 라는 Linear를 그린다... 이때 shape 지정이 중요
linear=nn.Linear(3,2) # w는 (3,2) b는 (10,3)
print(linear.weight) # 내부적으로 transpose 되어서 나옴
print(linear.bias) # (10,2)가 아닌 1행만 나옴... 행이 다 같기 때문에

linear.parameters() # 학습주체(Parameter)들을 packing해서 가지고 있음

Parameter containing:
tensor([[ 0.0461, -0.0439,  0.5520],
        [ 0.4119, -0.4851,  0.1800]], requires_grad=True)
Parameter containing:
tensor([-0.4903,  0.3460], requires_grad=True)


<generator object Module.parameters at 0x00000213E94EE1C8>

In [218]:
# 2. Loss 힘수 정의
# 연속변수니까 MSE로 사용
loss_function = nn.MSELoss()

# 3. 학습 모델 정의 ... SGD
# 학습주체(param) 및 hyper param들을 지정
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# 4. 예측
pred = linear(x) # model에 x 입력하면 예측값이 나옴

# 5. 첫 Loss 값과 Loss 함수 도출
loss=loss_function(pred, y)
print('loss before backpropagation:: ', round(loss.item(),4)) # 값만 뽑기

# 6. Backpropagation_SGD
loss.backward()
print('dL/dw = {}, dL/db = {} ' .format(linear.weight.grad,linear.bias.grad))

# 7. 기울기를 바탕으로 param 재조정
optimizer.step() # 수정된 값으로 실질적인 학습 시작... 하강

# 8. 반복효과
pred = linear(x)
loss=loss_function(pred, y)
print('loss after backpropagation:: ', round(loss.item(),4))

loss before backpropagation::  2.1032
dL/dw = tensor([[ 0.2010, -0.8274,  2.5154],
        [ 1.3399, -2.1158,  2.2961]]), dL/db = tensor([-0.4912,  0.3995]) 
loss after backpropagation::  2.0106


In [220]:
list(linear.parameters())

[Parameter containing:
 tensor([[ 0.0430, -0.0314,  0.5142],
         [ 0.3918, -0.4532,  0.1455]], requires_grad=True),
 Parameter containing:
 tensor([-0.4830,  0.3400], requires_grad=True)]